apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: colorapp
  template:
    metadata:
      labels:
        app: colorapp
    spec:
      containers:
        - name: colorapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
          - name: "APP_COLOR"
            value: "{{ .Values.appenv.appcolor }}"